name: First Workflow
on: 
  workflow_dispatch:
  push:
    branches:
      - gh-action*
jobs:
  my_job:
    name: greetings job
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: |
          time=`date +'%H:%m'`
          echo "Hello world"
          echo "The time is $time"
